# Generated by Django 4.1.7 on 2023-05-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('cnp', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('date_of_birth', models.DateTimeField(verbose_name='Date Of Birth')),
                ('join_date', models.DateTimeField(verbose_name='Date of Join')),
                ('expiry_date', models.DateTimeField(verbose_name='Expiry date')),
            ],
        ),
    ]
